"""initial migrations

Revision ID: 15737b75007b
Revises:
Create Date: 2026-04-21 21:52:54.777116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15737b75007b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("asset_class", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("isin", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_index("ix_assets_asset_class", "assets", ["asset_class"], unique=False)
    op.create_index("ix_assets_sector", "assets", ["sector"], unique=False)
    op.create_index("ix_assets_ticker", "assets", ["ticker"], unique=False)
    op.create_table(
        "benchmarks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_index("ix_benchmarks_ticker", "benchmarks", ["ticker"], unique=False)
    op.create_table(
        "csv_import_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("column_mapping", sa.JSON(), nullable=False),
        sa.Column("date_format", sa.String(length=50), nullable=True),
        sa.Column("delimiter", sa.CHAR(length=1), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_csv_import_profiles_name", "csv_import_profiles", ["name"], unique=False
    )
    op.create_table(
        "fx_rates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("to_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_currency", "to_currency", "date", name="uq_fx_rates_currencies_date"
        ),
    )
    op.create_index(
        "ix_fx_rates_currencies",
        "fx_rates",
        ["from_currency", "to_currency"],
        unique=False,
    )
    op.create_index("ix_fx_rates_date", "fx_rates", ["date"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("base_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_portfolios_base_currency", "portfolios", ["base_currency"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "target_net_worth", sa.Numeric(precision=20, scale=2), nullable=False
        ),
        sa.Column("target_net_worth_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("monthly_savings", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("monthly_savings_currency", sa.CHAR(length=3), nullable=False),
        sa.Column(
            "expected_annual_return", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_goals_portfolio_id", "goals", ["portfolio_id"], unique=False)
    op.create_index("ix_goals_target_date", "goals", ["target_date"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "date", name="uq_price_history_asset_date"),
    )
    op.create_index(
        "ix_price_history_asset_id", "price_history", ["asset_id"], unique=False
    )
    op.create_index("ix_price_history_date", "price_history", ["date"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("trade_type", sa.String(length=20), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("trade_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("fees", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("import_batch_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trades_asset_id", "trades", ["asset_id"], unique=False)
    op.create_index(
        "ix_trades_import_batch_id", "trades", ["import_batch_id"], unique=False
    )
    op.create_index("ix_trades_portfolio_id", "trades", ["portfolio_id"], unique=False)
    op.create_index("ix_trades_trade_date", "trades", ["trade_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trades_trade_date", table_name="trades")
    op.drop_index("ix_trades_portfolio_id", table_name="trades")
    op.drop_index("ix_trades_import_batch_id", table_name="trades")
    op.drop_index("ix_trades_asset_id", table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_price_history_date", table_name="price_history")
    op.drop_index("ix_price_history_asset_id", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index("ix_goals_target_date", table_name="goals")
    op.drop_index("ix_goals_portfolio_id", table_name="goals")
    op.drop_table("goals")
    op.drop_index("ix_portfolios_base_currency", table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_index("ix_fx_rates_date", table_name="fx_rates")
    op.drop_index("ix_fx_rates_currencies", table_name="fx_rates")
    op.drop_table("fx_rates")
    op.drop_index("ix_csv_import_profiles_name", table_name="csv_import_profiles")
    op.drop_table("csv_import_profiles")
    op.drop_index("ix_benchmarks_ticker", table_name="benchmarks")
    op.drop_table("benchmarks")
    op.drop_index("ix_assets_ticker", table_name="assets")
    op.drop_index("ix_assets_sector", table_name="assets")
    op.drop_index("ix_assets_asset_class", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
